### PR TITLE
Refactor UI

### PR DESCRIPTION
**Pull request by Ulydev**
Refactoring of some UI elements

### CODE REVIEW

**Comment by Ulydev** [comment]
Screenshot_1587064419
Screenshot_1587064264
Screenshot_1587064260
Screenshot_1587063860

**Comment by Ulydev** [comment]
- tests fail because of UI changes
- history doesn't work, need to investigate

**Review by AdrienRem — COMMENTED** [review]
The new UI is really pretty !

If the textView is too difficult to get working again don't spend too much time on it. We will replace it with a map soon anyway.

You need to add a few translations too

**Comment by Ulydev** [comment]
yes I'm still finishing the merge. it's huge.
which textView are you talking about? in the History fragment?

**Review by lucieho — APPROVED** [review]
Very nice looking UI!
- Good idea to simplify and add "more" button to UI.
- The UI is now more flexible with to the conversion from activity to fragment.
- Good to replace deprecated appcompatactivity with activity.
- Icons and History as a DialogFragment make the app more intuitive and nicer to look at

Well done

**Review by AdrienRem — APPROVED** [review]
Yes I was talking about the history fragment

**Pull request merged**
