### PR TITLE
Feature/firebase

### PR DESCRIPTION
**Pull request by TheBlueHawk**
Firebase support added to the app
Firebase support added for users

### CODE REVIEW

**Comment by AdrienRem** [comment]
Ok !

**Review by AdrienRem — APPROVED** [review]
Ok !

**Review by Ulydev — APPROVED** [review]
Let's get this merged! Great work!

**Review by lucieho — APPROVED** [review]

**Review by TheCrazyKing — APPROVED** [review]
LGTM

**Pull request closed without merging**
