### PR TITLE
App name, icon, privacy slide

### PR DESCRIPTION
**Pull request by Ulydev**
This PR changes the name of the app to "Virus Tracker" (better for the demo but can be changed later), adds a draft icon, and an explanation slide on privacy in the intro.
These three additions are not made into separate PRs since they aren't introducing any breaking code / asset changes.

### CODE REVIEW

**Comment by Ulydev** [comment]
Privacy slide
Screenshot_1589432883

**Comment by Ulydev** [comment]
App icon on dashboard
Screen Shot 2020-05-14 at 07 07 49

**Comment by Ulydev** [comment]
granted we could brainstorm more on the icon because it's quite basic

**Review by TheBlueHawk — CHANGES_REQUESTED** [review]
Very nice looking! But we should update the testCanNavigateToSignIn() to take into account the new slide, it's a one-line change I take care of that

**Review by Ulydev — COMMENTED** [review]
yup thanks for noticing :-)

**Review by TheBlueHawk — APPROVED** [review]

**Review by TheCrazyKing — APPROVED** [review]
Nice work, nothing to say

**Pull request merged**
