### PR TITLE
Enhancement/better intro

### PR DESCRIPTION
**Pull request by Ulydev**
New intro

### CODE REVIEW

**Comment by Ulydev** [comment]
Screenshot_1588873265

Screenshot_1588873274

Screenshot_1588873279

Screenshot_1588873309

**Review by TheBlueHawk — APPROVED** [review]
Wow, such a cool design! Maybe in the future we should also include a screen about privacy / user data protection, but this will be for a next PR. Good job!

**Review by lucieho — APPROVED** [review]
Nice creativity! Makes the app more intuitive
I agree with TheBlueHawk's suggestion about some slide on privacy features.
Well done!

**Comment by Ulydev** [comment]
Agreed, let's add this on the next PR.

**Pull request merged**
