### PR TITLE
Move map buttons into main FAB with list view

### PR DESCRIPTION
**Pull request by Ulydev**

### CODE REVIEW

**Comment by Ulydev** [comment]
Screenshot_1591215935

**Review by AdrienRem — APPROVED** [review]
It's very well done, thank you ! Can you make the magnifying glass the same share of gray as the rest of the icons ?

**Review by lucieho — APPROVED** [review]
So much prettier! Nice job
Maybe we should add an intro slide to explain the goal of these buttons, but that's for another pr

**Comment by Ulydev** [comment]
> It's very well done, thank you ! Can you make the magnifying glass the same share of gray as the rest of the icons ?

Good catch!! You have quite the hawk's eye. Like @TheBlueHawk !

**Pull request merged**
