### PR TITLE
Dev/user encapsulations

### PR DESCRIPTION
**Pull request by TheCrazyKing**
This does a little bit of refactoring of how User is encapsulated. Basically, it adds a "IN_TEST" static variable to simplify things, renames the factory to an adapter, and remove useless Account properties (ex. PlayId support , ...)

### CODE REVIEW

**Comment by TheCrazyKing** [comment]
Maybe I could try to add some tests but I don't see how right now

**Review by TheBlueHawk — APPROVED** [review]
Good work, by removing the getters and limiting the use of the google account we have a much better encapsulation that protects user data!

**Review by lucieho — APPROVED** [review]
Nice cleaning!

**Review by AdrienRem — APPROVED** [review]
The adapter is indeed a better name for what this class is doing

**Pull request merged**
